"""Assistant Presentation Layer — Pydantic Schemas."""

from __future__ import annotations

from datetime import datetime
from typing import Any, Generic, TypeVar
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field

from app.modules.travel.assistant.domain.enums import (
    ActionStatus,
    AssistantActionType,
    AssistantResponseType,
)
from app.modules.travel.budget.presentation.schemas import (
    BudgetResponse,
    ExpenseResponse,
)
from app.modules.travel.itinerary.presentation.schemas import ItineraryResponse

T = TypeVar("T")


class DataEnvelope(BaseModel, Generic[T]):
    """Standard API response envelope."""

    data: T
    meta: dict[str, Any] = Field(default_factory=dict)


class ChatMessageSchema(BaseModel):
    """A message in the chat history."""

    role: str = Field(..., description="Role: 'user' or 'assistant' or 'system'")
    content: str = Field(..., description="Message text content")
    timestamp: datetime | None = None


class PersistedMessageSchema(BaseModel):
    """A persisted message from the database."""

    model_config = ConfigDict(from_attributes=True)

    message_id: UUID
    role: str
    content: str
    response_type: AssistantResponseType | None = None
    action_id: UUID | None = None
    tools_used: list[AssistantActionType] = Field(default_factory=list)
    created_at: datetime


class ConversationHistoryResponse(BaseModel):
    """Full conversation history for a trip and user."""

    conversation_id: UUID
    trip_id: UUID
    user_id: UUID
    messages: list[PersistedMessageSchema] = Field(default_factory=list)


class ProposedActionSchema(BaseModel):
    """Structured proposal generated by AI Assistant requiring user confirmation."""

    model_config = ConfigDict(from_attributes=True)

    action_id: UUID
    trip_id: UUID
    action_type: AssistantActionType
    summary: str
    description: str
    payload: dict[str, Any]
    status: ActionStatus
    created_at: datetime
    applied_at: datetime | None = None


class ChatAssistantRequest(BaseModel):
    """Request payload for trip assistant chat."""

    message: str = Field(..., min_length=1, max_length=2000, description="User message prompt")
    history: list[ChatMessageSchema] = Field(
        default_factory=list, description="Recent conversation turns (optional client-side echo)"
    )


class ChatAssistantResponse(BaseModel):
    """Response payload returned by AI Assistant."""

    message: str
    response_type: AssistantResponseType
    proposed_action: ProposedActionSchema | None = None
    tools_used: list[AssistantActionType] = Field(default_factory=list)


class ConfirmActionResponse(BaseModel):
    """Response returned when an action is confirmed and applied."""

    action: ProposedActionSchema
    itinerary: ItineraryResponse | None = None
    expense: ExpenseResponse | None = None
    budget: BudgetResponse | None = None
    message: str = "Action applied successfully."


class RejectActionResponse(BaseModel):
    """Response returned when an action is cancelled/rejected."""

    action: ProposedActionSchema
    message: str = "Action cancelled."


class TravelWarningSchema(BaseModel):
    """Proactive travel intelligence warning schema."""

    warning_id: str
    category: str
    severity: str
    title: str
    message: str
    day_number: int | None = None
    item_ids: list[str] = Field(default_factory=list)
    metadata: dict[str, Any] = Field(default_factory=dict)


class TripWarningsResponse(BaseModel):
    """Aggregated trip warnings response."""

    trip_id: UUID
    warnings: list[TravelWarningSchema] = Field(default_factory=list)
    total_warnings: int
    has_critical: bool
    itinerary_conflicts_count: int
    budget_risks_count: int
