"""
PlainRefreshToken value object.

Represents the opaque 256-bit token returned to clients after login or rotation.
This value is NEVER stored anywhere — only its SHA-256 hash is persisted.

Security contract:
  - __repr__ and __str__ always return [REDACTED].
  - f-strings, logging %s formatters, and exception messages never reveal the token.
  - Raw value is accessible only via as_client_token() — the intent-revealing name
    signals "only call this when you are about to send the value to the HTTP response."
"""

from __future__ import annotations

import secrets
from dataclasses import dataclass, field

from app.shared.domain.value_object import ValueObject

# 32 bytes = 256 bits of entropy; URL-safe base64 encodes to 43 characters.
_TOKEN_BYTE_LENGTH = 32


@dataclass(frozen=True)
class PlainRefreshToken(ValueObject):
    """
    The opaque 256-bit refresh token value to deliver to the client.

    Generated by PlainRefreshToken.generate() using a CSPRNG.
    Never stored or logged. Only the SHA-256 hash is persisted.

    Two ways to create:
      PlainRefreshToken.generate()         — new 256-bit token for issuance
      PlainRefreshToken.from_client(str)   — wraps a client-presented token for hashing
    """

    value: str = field(repr=False)

    def __repr__(self) -> str:
        return "PlainRefreshToken([REDACTED])"

    def __str__(self) -> str:
        return "[REDACTED]"

    @classmethod
    def generate(cls) -> "PlainRefreshToken":
        """
        Generate a cryptographically secure 256-bit opaque refresh token.

        Uses secrets.token_urlsafe(32): 32 bytes from os.urandom,
        URL-safe base64 encoded. Result is 43 characters, URL-safe.
        """
        return cls(value=secrets.token_urlsafe(_TOKEN_BYTE_LENGTH))

    @classmethod
    def from_client(cls, token_str: str) -> "PlainRefreshToken":
        """
        Wrap a client-provided token string for hashing and lookup.

        Does NOT generate new entropy. Use only when processing an incoming
        HTTP request that contains a previously issued refresh token.
        """
        return cls(value=token_str)

    def as_client_token(self) -> str:
        """
        Return the raw URL-safe token string to include in the HTTP response.

        Only call this immediately before serialising to the response body.
        Never pass the return value to a logger, exception, or repr call.
        """
        return self.value
