"""TripProposalModel — SQLAlchemy ORM model for the trip_proposals table."""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import (
    JSON,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    text,
)
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, declared_attr, mapped_column

from app.core.db.mixins import (
    OptimisticLockMixin,
    SoftDeleteMixin,
    TimestampMixin,
    UUIDPrimaryKeyMixin,
)
from app.database import Base


class TripProposalModel(
    UUIDPrimaryKeyMixin,
    TimestampMixin,
    SoftDeleteMixin,
    OptimisticLockMixin,
    Base,
):
    """ORM model for the trip_proposals table."""

    __tablename__ = "trip_proposals"

    # ---------------------------------------------------------------------- #
    # Foreign keys & owner information                                         #
    # ---------------------------------------------------------------------- #

    owner_id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
        comment="User who owns this proposal.",
        sort_order=1,
    )

    trip_id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("trips.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
        comment="Trip being planned.",
        sort_order=2,
    )

    # ---------------------------------------------------------------------- #
    # Business fields                                                          #
    # ---------------------------------------------------------------------- #

    status: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        server_default=text("'queued'"),
        comment="Current lifecycle status of the proposal.",
        sort_order=3,
    )

    # PlanningPreferences flattened columns
    destination: Mapped[str] = mapped_column(
        String(200),
        nullable=False,
        comment="Target destination.",
        sort_order=4,
    )

    duration_days: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        comment="Plan duration in days.",
        sort_order=5,
    )

    budget_level: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        comment="Budget level (budget, mid_range, luxury).",
        sort_order=6,
    )

    interests: Mapped[list[str]] = mapped_column(
        JSON,
        nullable=False,
        comment="Interests selected by user.",
        sort_order=7,
    )

    travel_style: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        comment="Travel style (relaxed, balanced, active).",
        sort_order=8,
    )

    special_requirements: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        server_default=text("''"),
        comment="Special accessibility, dietary, or custom requirements.",
        sort_order=9,
    )

    # PlanningResult flattened columns
    result_summary: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Plan summary generated by AI.",
        sort_order=10,
    )

    result_days: Mapped[list[dict[str, Any]] | None] = mapped_column(
        JSON,
        nullable=True,
        comment="Serialized day-by-day itinerary.",
        sort_order=11,
    )

    estimated_total_cost: Mapped[str | None] = mapped_column(
        String(50),
        nullable=True,
        comment="AI estimated total cost description.",
        sort_order=12,
    )

    generated_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        comment="UTC timestamp when the proposal was generated.",
        sort_order=13,
    )

    # Error fields
    failure_reason: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Details on why generation failed.",
        sort_order=14,
    )

    # TTL
    expires_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        comment="UTC timestamp when proposal expires.",
        sort_order=15,
    )

    # ---------------------------------------------------------------------- #
    # Optimistic locking                                                       #
    # ---------------------------------------------------------------------- #

    @declared_attr.directive  # type: ignore[override]
    def __mapper_args__(self) -> dict:  # type: ignore[override]
        return {"version_id_col": self.__table__.c.version}

    # ---------------------------------------------------------------------- #
    # Indexes and constraints                                                  #
    # ---------------------------------------------------------------------- #

    __table_args__ = (
        Index(
            "ix_trip_proposals_owner_id_created_at_active",
            "owner_id",
            "created_at",
            postgresql_where=text("deleted_at IS NULL"),
        ),
        CheckConstraint(
            "status IN ('queued', 'generating', 'ready', "
            "'accepted', 'rejected', 'failed', 'expired')",
            name="ck_trip_proposals_status",
        ),
        CheckConstraint(
            "budget_level IN ('budget', 'mid_range', 'luxury')",
            name="ck_trip_proposals_budget_level",
        ),
        CheckConstraint(
            "travel_style IN ('relaxed', 'balanced', 'active')",
            name="ck_trip_proposals_travel_style",
        ),
    )

    def __repr__(self) -> str:
        return (
            f"TripProposalModel("
            f"id={self.id!r}, "
            f"trip_id={self.trip_id!r}, "
            f"status={self.status!r}"
            f")"
        )
