"""Create trip proposals table.

Revision ID: 20260714_0004
Revises: 20260710_0003
Create Date: 2026-07-14
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260714_0004"
down_revision: str | None = "20260710_0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the trip proposals schema."""
    op.create_table(
        "trip_proposals",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
            comment="UUID v4 primary key.",
        ),
        sa.Column(
            "owner_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", name="fk_trip_proposals_owner_id_users", ondelete="RESTRICT"),
            nullable=False,
            comment="User who owns this proposal.",
        ),
        sa.Column(
            "trip_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("trips.id", name="fk_trip_proposals_trip_id_trips", ondelete="RESTRICT"),
            nullable=False,
            comment="Trip being planned.",
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            server_default=sa.text("'queued'"),
            comment="Current lifecycle status.",
        ),
        sa.Column(
            "destination",
            sa.String(length=200),
            nullable=False,
            comment="Target destination.",
        ),
        sa.Column(
            "duration_days",
            sa.Integer(),
            nullable=False,
            comment="Plan duration in days.",
        ),
        sa.Column(
            "budget_level",
            sa.String(length=20),
            nullable=False,
            comment="Budget tier selected.",
        ),
        sa.Column(
            "interests",
            sa.JSON(),
            nullable=False,
            comment="Selected interest tags.",
        ),
        sa.Column(
            "travel_style",
            sa.String(length=20),
            nullable=False,
            comment="Travel style preference.",
        ),
        sa.Column(
            "special_requirements",
            sa.Text(),
            nullable=False,
            server_default="",
            comment="Custom requirements.",
        ),
        sa.Column(
            "result_summary",
            sa.Text(),
            nullable=True,
            comment="Plan summary generated by AI.",
        ),
        sa.Column(
            "result_days",
            sa.JSON(),
            nullable=True,
            comment="Serialized day-by-day itinerary.",
        ),
        sa.Column(
            "estimated_total_cost",
            sa.String(length=50),
            nullable=True,
            comment="Estimated total cost string.",
        ),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="UTC timestamp when proposal was generated.",
        ),
        sa.Column(
            "failure_reason",
            sa.Text(),
            nullable=True,
            comment="AI generation error reason.",
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="UTC timestamp when proposal expires.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "deleted_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "version",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("1"),
            comment="Optimistic concurrency version.",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_trip_proposals"),
        sa.CheckConstraint(
            "status IN ('queued', 'generating', 'ready', 'accepted', 'rejected', 'failed', 'expired')",
            name="ck_trip_proposals_status",
        ),
        sa.CheckConstraint(
            "budget_level IN ('budget', 'mid_range', 'luxury')",
            name="ck_trip_proposals_budget_level",
        ),
        sa.CheckConstraint(
            "travel_style IN ('relaxed', 'balanced', 'active')",
            name="ck_trip_proposals_travel_style",
        ),
    )

    # --- Indexes ---
    op.create_index(
        "ix_trip_proposals_owner_id_created_at_active",
        "trip_proposals",
        ["owner_id", "created_at"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "ix_trip_proposals_trip_id",
        "trip_proposals",
        ["trip_id"],
        unique=False,
    )
    op.create_index(
        "ix_trip_proposals_deleted_at",
        "trip_proposals",
        ["deleted_at"],
        unique=False,
    )

    # --- Triggers ---
    op.execute(
        """
        CREATE TRIGGER trg_trip_proposals_updated_at
        BEFORE UPDATE ON trip_proposals
        FOR EACH ROW EXECUTE FUNCTION set_updated_at();
        """
    )


def downgrade() -> None:
    """Remove the trip proposals schema."""
    op.execute("DROP TRIGGER IF EXISTS trg_trip_proposals_updated_at ON trip_proposals")

    op.drop_index("ix_trip_proposals_deleted_at", table_name="trip_proposals")
    op.drop_index("ix_trip_proposals_trip_id", table_name="trip_proposals")
    op.drop_index("ix_trip_proposals_owner_id_created_at_active", table_name="trip_proposals")

    op.drop_table("trip_proposals")
