"""AssistantEngine Protocol and Result Types."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Protocol, runtime_checkable

from app.modules.travel.assistant.domain.enums import (
    AssistantActionType,
    AssistantResponseType,
)
from app.modules.travel.assistant.domain.value_objects import ChatMessage


@dataclass(frozen=True)
class ProposedActionData:
    """Raw structured proposed action generated by the AI engine."""

    action_type: AssistantActionType
    summary: str
    description: str
    payload: dict[str, Any]


@dataclass(frozen=True)
class AssistantEngineResult:
    """Output from the AI Assistant Engine."""

    message: str
    response_type: AssistantResponseType
    proposed_action: ProposedActionData | None = None
    tools_used: tuple[AssistantActionType, ...] = ()


@runtime_checkable
class AssistantEngine(Protocol):
    """Protocol defining the conversational travel assistant engine interface."""

    async def chat(
        self,
        *,
        context: dict[str, Any],
        user_message: str,
        history: list[ChatMessage] | None = None,
    ) -> AssistantEngineResult:
        """Process user message in the context of a trip and return structured response."""
        ...
