"""
Immutable per-request context for the Authentication presentation layer.

Extracted once per request by get_request_context() and injected into
route handlers as a single object. Keeps handler signatures clean — one
context argument instead of many individual header parameters.

Headers consumed:
  X-Request-ID       → request_id  (set or generated by RequestIDMiddleware)
  X-Correlation-ID   → correlation_id (propagated from async jobs)
  X-Forwarded-For    → ip_address (leftmost = real client IP)
  User-Agent         → user_agent
  Accept-Language    → locale (future i18n)
  X-Timezone         → timezone (future tz-aware responses)
  X-App-Version      → app_version (future version-specific behaviour)

The received_at timestamp is captured at dependency resolution time
(within the same async task as the request). It is accurate to within
a few milliseconds of the actual network arrival and is used as the
session.created_at in registration responses.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass
from datetime import UTC, datetime
from typing import Annotated

from fastapi import Depends, Request

from app.core.middleware.request_id import get_correlation_id, get_request_id


@dataclass(frozen=True)
class RequestContext:
    """
    Immutable snapshot of per-request context.

    Created by get_request_context() and injected into route handlers.
    Carries tracing IDs, client metadata, and the server-side arrival
    timestamp — all information that is HTTP-transport-level, not business-level.
    """

    request_id: str
    correlation_id: str
    ip_address: str | None
    user_agent: str | None
    locale: str | None
    timezone: str | None
    app_version: str | None
    received_at: datetime


def _extract_client_ip(request: Request) -> str | None:
    """
    Extract the real client IP from the request.

    Priority: X-Forwarded-For (reverse proxy / load balancer) → X-Real-IP →
    REMOTE_ADDR from the ASGI scope.

    Only the leftmost address in X-Forwarded-For is used — it is the
    originating client. Subsequent addresses are added by each proxy hop
    and should not be trusted as the client.
    """
    forwarded_for = request.headers.get("X-Forwarded-For")
    if forwarded_for:
        return forwarded_for.split(",")[0].strip()
    real_ip = request.headers.get("X-Real-IP")
    if real_ip:
        return real_ip.strip()
    if request.client:
        return request.client.host
    return None


async def get_request_context(request: Request) -> RequestContext:
    """
    FastAPI dependency: extract and return a RequestContext for the current request.

    The request_id falls back to a fresh UUID v4 if RequestIDMiddleware has
    not populated the ContextVar (e.g., in tests that skip middleware).

    Usage in a route handler::

        async def my_handler(
            ctx: Annotated[RequestContext, Depends(get_request_context)],
        ) -> ...:
            ...
    """
    return RequestContext(
        request_id=get_request_id() or str(uuid.uuid4()),
        correlation_id=get_correlation_id(),
        ip_address=_extract_client_ip(request),
        user_agent=request.headers.get("User-Agent"),
        locale=request.headers.get("Accept-Language"),
        timezone=request.headers.get("X-Timezone"),
        app_version=request.headers.get("X-App-Version"),
        received_at=datetime.now(UTC),
    )


# Annotated shorthand for route function signatures
CurrentRequestContext = Annotated[RequestContext, Depends(get_request_context)]
