"""
Pydantic v2 schemas for the Authentication presentation layer.

These schemas perform TRANSPORT-LEVEL validation only:
  - Type coercion and whitespace stripping
  - Field presence and maximum length (hard transport caps)
  - Enum membership for enumerated fields (e.g. platform)

They do NOT perform BUSINESS validation:
  - Email format and MX record validity → Email value object (domain layer)
  - Password strength → PasswordStrengthPolicy (application layer)
  - Email uniqueness → AuthenticationRepository (infrastructure layer)

Any business rule here would duplicate domain logic and create an
inconsistency surface — the API layer would reject before the domain
can produce a structured error response.

Schema → OpenAPI mapping:
  All schemas are generated by FastAPI into the /openapi.json document.
  Field descriptions, examples, and constraints feed directly into
  the Swagger UI and ReDoc documentation. Keep them accurate.
"""

from __future__ import annotations

from datetime import datetime
from typing import Annotated, Generic, Literal, TypeVar

from pydantic import BaseModel, ConfigDict, Field

T = TypeVar("T")


# ──────────────────────────────────────────────────────────────────────────── #
# Generic response envelope                                                      #
# ──────────────────────────────────────────────────────────────────────────── #


class DataEnvelope(BaseModel, Generic[T]):
    """
    Standard single-resource success envelope.

    All success responses from the Authentication API are wrapped in::

        { "data": <payload> }

    This shape matches the Authentication API Contract §3.1.
    """

    model_config = ConfigDict(populate_by_name=True)

    data: T


# ──────────────────────────────────────────────────────────────────────────── #
# Shared sub-schemas                                                            #
# ──────────────────────────────────────────────────────────────────────────── #


class DeviceInfoRequest(BaseModel):
    """
    Optional device metadata sent with registration or login requests.

    Used to populate the AuthenticationSession for session-management
    display (e.g., "Alice's iPhone 15 Pro" in a devices list).

    All fields are optional. Omitting this object is valid.
    Transport caps are enforced; values beyond the cap are rejected with 422.
    """

    model_config = ConfigDict(str_strip_whitespace=True, extra="ignore")

    device_name: Annotated[
        str | None,
        Field(
            default=None,
            max_length=100,
            description="Human-readable device name. Shown in session management screens.",
            examples=["Alice's iPhone 15 Pro"],
        ),
    ] = None

    platform: Annotated[
        Literal["ios", "android", "web"] | None,
        Field(
            default=None,
            description='Client platform. One of: "ios", "android", "web".',
        ),
    ] = None

    app_version: Annotated[
        str | None,
        Field(
            default=None,
            max_length=20,
            description='Semver app version string (e.g. "1.0.0").',
            examples=["1.0.0"],
        ),
    ] = None

    os_version: Annotated[
        str | None,
        Field(
            default=None,
            max_length=50,
            description='Operating system version string (e.g. "iOS 17.4").',
            examples=["iOS 17.4"],
        ),
    ] = None


class SessionResponse(BaseModel):
    """
    Session summary embedded in token responses.

    Returned only when a session was created (dev/CI with auto-verify,
    or production after email is verified). Matches §3.4 of the API contract.
    """

    model_config = ConfigDict(populate_by_name=True)

    session_id: Annotated[
        str,
        Field(description="UUID identifying the newly created session."),
    ]
    device_name: Annotated[
        str | None,
        Field(
            description=(
                "Device name provided in the request. Null if not supplied."
            )
        ),
    ]
    created_at: Annotated[
        datetime,
        Field(description="ISO 8601 UTC timestamp when the session was created."),
    ]


# ──────────────────────────────────────────────────────────────────────────── #
# POST /register — Request schema                                                #
# ──────────────────────────────────────────────────────────────────────────── #


class RegisterRequest(BaseModel):
    """
    POST /api/v1/auth/register request body.

    Transport-level validation enforced here:
      - email: non-empty, max 254 characters (RFC 5321 limit), whitespace stripped.
      - password: non-empty, max 128 characters (hard cap; prevents
        algorithmic-complexity attacks on the hashing layer).
      - device_info: optional nested object.

    Business validation NOT performed here (application layer handles these):
      - Email format / RFC 5322 compliance → InvalidEmailError (422)
      - Password strength → WeakPasswordError (422)
      - Email uniqueness → EmailAlreadyExistsError (409)
    """

    model_config = ConfigDict(str_strip_whitespace=True)

    email: Annotated[
        str,
        Field(
            min_length=1,
            max_length=254,
            description=(
                "The user's email address. "
                "Normalised (lowercased and stripped) server-side before storage. "
                "Display the server-returned email value, not the raw user input."
            ),
            examples=["alice@example.com"],
        ),
    ]

    password: Annotated[
        str,
        Field(
            min_length=1,
            max_length=128,
            description=(
                "Account password in plaintext (sent over TLS). "
                "Strength requirements are enforced server-side (12–128 characters). "
                "Never logged, stored, or echoed."
            ),
        ),
    ]

    device_info: Annotated[
        DeviceInfoRequest | None,
        Field(
            default=None,
            description=(
                "Optional device metadata for session display. "
                "Ignored when no session is created (verification required)."
            ),
        ),
    ] = None


# ──────────────────────────────────────────────────────────────────────────── #
# POST /login — Request schema                                                   #
# ──────────────────────────────────────────────────────────────────────────── #


class LoginRequest(BaseModel):
    """
    POST /api/v1/auth/login request body.

    Transport-level validation enforced here:
      - email: non-empty, max 254 characters, whitespace stripped.
      - password: non-empty, max 128 characters (hard cap; prevents
        algorithmic-complexity attacks on the hashing layer).
      - device_info: optional nested object (same shape as registration).
      - locale: optional BCP 47 locale tag for localised error messages.
      - timezone: optional IANA timezone name for timezone-aware responses.

    Business validation NOT performed here (application layer handles these):
      - Email format / RFC 5322 compliance → InvalidEmailError (422)
      - Credential correctness → InvalidCredentialsError (401)
      - Account state → AccountLockedError (423) / AccountDisabledError (403)
      - Email verification → EmailNotVerifiedError (403)
    """

    model_config = ConfigDict(str_strip_whitespace=True)

    email: Annotated[
        str,
        Field(
            min_length=1,
            max_length=254,
            description=(
                "The user's registered email address. "
                "Normalised (lowercased and stripped) server-side before lookup."
            ),
            examples=["alice@example.com"],
        ),
    ]

    password: Annotated[
        str,
        Field(
            min_length=1,
            max_length=128,
            description=(
                "Account password in plaintext (sent over TLS). "
                "Never logged, stored in logs, or echoed in any response."
            ),
        ),
    ]

    device_info: Annotated[
        DeviceInfoRequest | None,
        Field(
            default=None,
            description=(
                "Optional device metadata for session display. "
                "Used to populate the session's device_name in session lists."
            ),
        ),
    ] = None

    locale: Annotated[
        str | None,
        Field(
            default=None,
            max_length=35,
            description=(
                "BCP 47 locale tag (e.g. 'en-US', 'fr-FR'). "
                "Overrides Accept-Language for localised server responses."
            ),
            examples=["en-US"],
        ),
    ] = None

    timezone: Annotated[
        str | None,
        Field(
            default=None,
            max_length=50,
            description=(
                "IANA timezone name (e.g. 'America/New_York'). "
                "Used for timezone-aware timestamps in responses."
            ),
            examples=["America/New_York"],
        ),
    ] = None


# ──────────────────────────────────────────────────────────────────────────── #
# POST /login — Response schemas                                                 #
# ──────────────────────────────────────────────────────────────────────────── #


class UserResponse(BaseModel):
    """
    Authenticated user summary embedded in the login response.

    Returned as the `user` field in LoginResponse. Provides only the fields
    the client needs immediately after login — not the full user profile.
    """

    model_config = ConfigDict(populate_by_name=True)

    user_id: Annotated[
        str,
        Field(description="Stable UUID identifying the authenticated user account."),
    ]

    email: Annotated[
        str,
        Field(
            description=(
                "Normalised (lowercase, stripped) email address. "
                "Display this value to the user, not the raw value they typed."
            ),
        ),
    ]

    is_email_verified: Annotated[
        bool,
        Field(
            description=(
                "True if the user has verified their email address. "
                "Always True on a successful login when email verification is required."
            ),
        ),
    ]


class LoginResponse(BaseModel):
    """
    POST /api/v1/auth/login 200 response body (the `data` field).

    Always issued on a successful login — all token fields are present.
    Unlike RegisterResponse, there is no conditional shape: a successful
    login always creates a session and always issues tokens.

    Client integration:
      - Store `refresh_token` in Flutter Secure Storage. Keep `access_token`
        in memory only — never persist it.
      - Replace both tokens on every successful POST /refresh call.
      - Use `access_token_expires_at` to proactively refresh before expiry.
      - Display `user.email` (server-normalised), not the raw user input.
    """

    model_config = ConfigDict(populate_by_name=True)

    access_token: Annotated[
        str,
        Field(
            description=(
                "JWT access token (15-minute lifetime). "
                "Store in memory only — never persist to disk or logs."
            ),
        ),
    ]

    refresh_token: Annotated[
        str,
        Field(
            description=(
                "Opaque refresh token (7-day lifetime). "
                "Store in Flutter Secure Storage. "
                "Immediately replace on every successful POST /refresh call."
            ),
        ),
    ]

    token_type: Annotated[
        str,
        Field(
            examples=["Bearer"],
            description='Token type. Always "Bearer".',
        ),
    ]

    access_token_expires_at: Annotated[
        datetime,
        Field(description="ISO 8601 UTC timestamp when the access token expires."),
    ]

    refresh_token_expires_at: Annotated[
        datetime,
        Field(description="ISO 8601 UTC timestamp when the refresh token expires."),
    ]

    session: Annotated[
        SessionResponse,
        Field(description="Summary of the newly created session."),
    ]

    user: Annotated[
        UserResponse,
        Field(description="Authenticated user summary."),
    ]


# ──────────────────────────────────────────────────────────────────────────── #
# POST /register — Response schema                                               #
# ──────────────────────────────────────────────────────────────────────────── #


class RegisterResponse(BaseModel):
    """
    POST /api/v1/auth/register 201 response body (the `data` field).

    Two variants, distinguished by `requires_verification`:

    **Production (requires_verification: true):**
    The account is created but email is unverified. No tokens are issued.
    Token fields (access_token, refresh_token, etc.) are absent.
    The user must complete `POST /verify-email` before logging in.

    **Dev / CI (requires_verification: false):**
    Email is auto-verified by server configuration. Tokens are issued
    immediately — same shape as the `POST /login` response.
    The client should navigate to the home screen using the returned tokens.

    This matches Authentication API Contract §5.1.
    """

    model_config = ConfigDict(populate_by_name=True)

    user_id: Annotated[
        str,
        Field(description="Stable UUID identifying the new user account."),
    ]

    email: Annotated[
        str,
        Field(
            description=(
                "Normalised (lowercase, stripped) email address. "
                "Display this value to the user, not the raw value they typed."
            ),
        ),
    ]

    requires_verification: Annotated[
        bool,
        Field(
            description=(
                "True: email not yet verified; no tokens issued; show 'check your email' screen. "
                "False: tokens issued immediately; navigate to home screen."
            ),
        ),
    ]

    message: Annotated[
        str | None,
        Field(
            default=None,
            description=(
                "Human-readable status message for display. "
                "Present when requires_verification is True."
            ),
        ),
    ] = None

    # ── Token fields (populated only when requires_verification is False) ── #

    access_token: Annotated[
        str | None,
        Field(
            default=None,
            description=(
                "JWT access token (15-minute lifetime). "
                "Store in memory only — never persist to disk. "
                "Dev/CI environments only."
            ),
        ),
    ] = None

    refresh_token: Annotated[
        str | None,
        Field(
            default=None,
            description=(
                "Opaque refresh token (7-day lifetime). "
                "Store in Flutter Secure Storage. "
                "Immediately replace on every successful POST /refresh call. "
                "Dev/CI environments only."
            ),
        ),
    ] = None

    token_type: Annotated[
        str | None,
        Field(
            default=None,
            examples=["Bearer"],
            description='Always "Bearer" when present.',
        ),
    ] = None

    access_token_expires_at: Annotated[
        datetime | None,
        Field(
            default=None,
            description="ISO 8601 UTC timestamp when the access token expires.",
        ),
    ] = None

    refresh_token_expires_at: Annotated[
        datetime | None,
        Field(
            default=None,
            description="ISO 8601 UTC timestamp when the refresh token expires.",
        ),
    ] = None

    session: Annotated[
        SessionResponse | None,
        Field(
            default=None,
            description=(
                "Session summary. "
                "Populated only when requires_verification is False."
            ),
        ),
    ] = None
